export enum MAIN_SECTIONS {
    HEADLINE = "HEADLINE",
    LOTTERY = "LOTTERY",
    RUSH = "RUSH",
    LEARN_MORE = "LEARN_MORE",
}

export enum LOTTERY_SECTIONS {
    HEADLINE = "HEADLINE",
    INTRO = "INTRO",
    HEADLAMP = "HEADLAMP",
    PIXEL_DESIGN = "PIXEL_DESIGN",
    WHEEL_DESIGN = "WHEEL_DESIGN",
    CUSTOM_DESIGN = "CUSTOM_DESIGN",
    NEW_COLOR = "NEW_COLOR",
    SMILE_BADGE = "SMILE_BADGE",
    SHORT_CUT = "SHORT_CUT",
}

export enum RUSH_SECTIONS {
    HEADLINE = "HEADLINE",
    INTRO = "INTRO",
    FAQ = "FAQ",
    ELECTRIC_REASON = "ELECTRIC_REASON",
    ELECTRIC_ADVANTAGE = "ELECTRIC_ADVANTAGE",
    REASON_FIRST = "REASON_FIRST",
    CASPER_FAR = "CASPER_FAR",
    CASPER_FAST = "CASPER_FAST",
    CASPER_COMFORTABLE = "CASPER_COMFORTABLE",
    REASON_SECOND = "REASON_SECOND",
    CASPER_WIDE = "CASPER_WIDE",
    CASPER_CHARGE = "CASPER_CHARGE",
    CASPER_SMART_KEY = "CASPER_SMART_KEY",
}

export enum CASPER_CUSTOM_SECTIONS {
    CUSTOM = "CUSTOM",
}

export enum CASPER_SHOWCASE_SECTIONS {
    SHOWCASE = "SHOWCASE",
}
